[package]
name = "qwe-2"
version = "0.1.0"
authors = ["@danielbintar <daniel.bintar@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
amethyst = "0.10.0"
reqwest = "0.9.8"
ws = "0.7.9"
url = "1.7.2"
